/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jeremy
 */
public class AtlasFrame extends javax.swing.JFrame {

    /**
     * Creates new form AtlasFrame
     */
    public AtlasFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        EnLabel = new javax.swing.JLabel();
        PrLabel = new javax.swing.JLabel();
        WeLabel = new javax.swing.JLabel();
        PoLabel = new javax.swing.JLabel();
        KnLabel = new javax.swing.JLabel();
        EnField = new javax.swing.JTextField();
        PrField = new javax.swing.JTextField();
        WeField = new javax.swing.JTextField();
        PoField = new javax.swing.JTextField();
        KnField = new javax.swing.JTextField();
        EnGoalField = new javax.swing.JTextField();
        PrGoalField = new javax.swing.JTextField();
        WeGoalField = new javax.swing.JTextField();
        PoGoalField = new javax.swing.JTextField();
        KnGoalField = new javax.swing.JTextField();
        statsLabel = new javax.swing.JLabel();
        goalsLabel = new javax.swing.JLabel();
        jSeparatorH = new javax.swing.JSeparator();
        jSeparatorV = new javax.swing.JSeparator();
        statusField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nationActionsLabel = new javax.swing.JLabel();
        EnHPButton = new javax.swing.JButton();
        PrHPButton = new javax.swing.JButton();
        WeHPButton = new javax.swing.JButton();
        KnHPButton = new javax.swing.JButton();
        PoHPButton = new javax.swing.JButton();
        nameAcceptButton = new javax.swing.JButton();
        updatesField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        playerActionsLabel = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        adjTerList = new javax.swing.JList();
        adjTerLabel = new javax.swing.JLabel();
        adjTerrainLabel = new javax.swing.JLabel();
        adjResourceLabel = new javax.swing.JLabel();
        terrainField = new javax.swing.JTextField();
        resourceField = new javax.swing.JTextField();
        curTerLabel = new javax.swing.JLabel();
        curTerrainLabel = new javax.swing.JLabel();
        curResourceLabel = new javax.swing.JLabel();
        curTerField = new javax.swing.JTextField();
        curTerrainField = new javax.swing.JTextField();
        curResourceField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));

        mapLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MapGraphic/MapHolder.png"))); // NOI18N

        nameField.setForeground(new java.awt.Color(204, 0, 0));
        nameField.setText("Name");
        nameField.setName(""); // NOI18N
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        EnLabel.setText("Environment");

        PrLabel.setText("Privacy");

        WeLabel.setText("Wealth");

        PoLabel.setText("Power");

        KnLabel.setText("Knowledge");

        EnField.setEditable(false);
        EnField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EnField.setText("0");

        PrField.setEditable(false);
        PrField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PrField.setText("0");
        PrField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrFieldActionPerformed(evt);
            }
        });

        WeField.setEditable(false);
        WeField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        WeField.setText("0");

        PoField.setEditable(false);
        PoField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PoField.setText("0");

        KnField.setEditable(false);
        KnField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        KnField.setText("0");

        EnGoalField.setEditable(false);
        EnGoalField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EnGoalField.setText("0");

        PrGoalField.setEditable(false);
        PrGoalField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PrGoalField.setText("0");

        WeGoalField.setEditable(false);
        WeGoalField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        WeGoalField.setText("0");

        PoGoalField.setEditable(false);
        PoGoalField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PoGoalField.setText("0");

        KnGoalField.setEditable(false);
        KnGoalField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        KnGoalField.setText("0");

        statsLabel.setText(": Stats");

        goalsLabel.setText(": Goals");

        jSeparatorH.setForeground(new java.awt.Color(0, 0, 0));

        jSeparatorV.setForeground(new java.awt.Color(0, 0, 0));
        jSeparatorV.setOrientation(javax.swing.SwingConstants.VERTICAL);

        statusField.setEditable(false);
        statusField.setText("Nomad");
        statusField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Status:");

        nationActionsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nationActionsLabel.setText("Nation Actions:");

        EnHPButton.setLabel("+HP");
        EnHPButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        EnHPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnHPButtonActionPerformed(evt);
            }
        });

        PrHPButton.setLabel("+HP");
        PrHPButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        PrHPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrHPButtonActionPerformed(evt);
            }
        });

        WeHPButton.setLabel("+HP");
        WeHPButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        WeHPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeHPButtonActionPerformed(evt);
            }
        });

        KnHPButton.setLabel("+HP");
        KnHPButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        KnHPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KnHPButtonActionPerformed(evt);
            }
        });

        PoHPButton.setLabel("+HP");
        PoHPButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        PoHPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PoHPButtonActionPerformed(evt);
            }
        });

        nameAcceptButton.setText("Accept");
        nameAcceptButton.setMargin(new java.awt.Insets(2, 2, 2, 2));

        updatesField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updatesField.setForeground(new java.awt.Color(0, 102, 0));
        updatesField.setText("Updates");

        jLabel2.setText("Updates:");

        playerActionsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        playerActionsLabel.setText("Player Actions:");

        jToggleButton1.setText("Travel");
        jToggleButton1.setMargin(new java.awt.Insets(2, 2, 2, 2));

        jScrollPane1.setViewportView(adjTerList);

        adjTerLabel.setText("Adjacent Territories:");

        adjTerrainLabel.setText("Terrain:");

        adjResourceLabel.setText("Resource:");

        terrainField.setEditable(false);
        terrainField.setText("terrain");
        terrainField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terrainFieldActionPerformed(evt);
            }
        });

        resourceField.setEditable(false);
        resourceField.setText("resource");

        curTerLabel.setText("Current Territory:");

        curTerrainLabel.setText("Terrain:");

        curResourceLabel.setText("Resource:");

        curTerField.setText("origin");
        curTerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curTerFieldActionPerformed(evt);
            }
        });

        curTerrainField.setText("terrain");

        curResourceField.setText("resource");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparatorH)
                            .addComponent(updatesField)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(playerActionsLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(adjResourceLabel)
                                            .addComponent(adjTerrainLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(terrainField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(resourceField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(curTerLabel)
                                            .addComponent(adjTerLabel)
                                            .addComponent(curTerrainLabel)
                                            .addComponent(curResourceLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(curTerrainField)
                                            .addComponent(curTerField)
                                            .addComponent(curResourceField, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))))
                                .addGap(0, 62, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mapLabel)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(EnLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(PrLabel))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(EnHPButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(EnGoalField)
                                            .addComponent(EnField))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PrGoalField)
                                            .addComponent(PrHPButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(PrField))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(WeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                    .addComponent(WeGoalField)
                                    .addComponent(WeField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(WeHPButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameAcceptButton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(PoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PoGoalField)
                                .addComponent(PoField)
                                .addComponent(PoHPButton, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(KnField)
                                    .addComponent(KnGoalField)
                                    .addComponent(KnHPButton, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(statsLabel)
                                    .addComponent(goalsLabel)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(statusField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(KnLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparatorV, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nationActionsLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparatorV)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(nameAcceptButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EnLabel)
                                    .addComponent(PrLabel)
                                    .addComponent(WeLabel)
                                    .addComponent(PoLabel)
                                    .addComponent(KnLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PrField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(WeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(KnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statsLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EnGoalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PrGoalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(WeGoalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PoGoalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(KnGoalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(goalsLabel)))
                            .addComponent(nationActionsLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EnHPButton)
                            .addComponent(PrHPButton)
                            .addComponent(WeHPButton)
                            .addComponent(KnHPButton)
                            .addComponent(PoHPButton))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mapLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparatorH, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playerActionsLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(curTerLabel)
                            .addComponent(curTerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(curTerrainLabel)
                            .addComponent(curTerrainField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(curResourceLabel)
                            .addComponent(curResourceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addComponent(adjTerLabel)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(adjTerrainLabel)
                                    .addComponent(terrainField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(adjResourceLabel)
                                    .addComponent(resourceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addComponent(jToggleButton1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updatesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrFieldActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void statusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusFieldActionPerformed

    private void EnHPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnHPButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnHPButtonActionPerformed

    private void PrHPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrHPButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrHPButtonActionPerformed

    private void WeHPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeHPButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WeHPButtonActionPerformed

    private void KnHPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KnHPButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KnHPButtonActionPerformed

    private void PoHPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PoHPButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PoHPButtonActionPerformed

    private void terrainFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terrainFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_terrainFieldActionPerformed

    private void curTerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curTerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_curTerFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtlasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtlasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtlasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtlasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtlasFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EnField;
    private javax.swing.JTextField EnGoalField;
    private javax.swing.JButton EnHPButton;
    private javax.swing.JLabel EnLabel;
    private javax.swing.JTextField KnField;
    private javax.swing.JTextField KnGoalField;
    private javax.swing.JButton KnHPButton;
    private javax.swing.JLabel KnLabel;
    private javax.swing.JTextField PoField;
    private javax.swing.JTextField PoGoalField;
    private javax.swing.JButton PoHPButton;
    private javax.swing.JLabel PoLabel;
    private javax.swing.JTextField PrField;
    private javax.swing.JTextField PrGoalField;
    private javax.swing.JButton PrHPButton;
    private javax.swing.JLabel PrLabel;
    private javax.swing.JTextField WeField;
    private javax.swing.JTextField WeGoalField;
    private javax.swing.JButton WeHPButton;
    private javax.swing.JLabel WeLabel;
    private javax.swing.JLabel adjResourceLabel;
    private javax.swing.JLabel adjTerLabel;
    private javax.swing.JList adjTerList;
    private javax.swing.JLabel adjTerrainLabel;
    private javax.swing.JTextField curResourceField;
    private javax.swing.JLabel curResourceLabel;
    private javax.swing.JTextField curTerField;
    private javax.swing.JLabel curTerLabel;
    private javax.swing.JTextField curTerrainField;
    private javax.swing.JLabel curTerrainLabel;
    private javax.swing.JLabel goalsLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparatorH;
    private javax.swing.JSeparator jSeparatorV;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel mapLabel;
    private javax.swing.JButton nameAcceptButton;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nationActionsLabel;
    private javax.swing.JLabel playerActionsLabel;
    private javax.swing.JTextField resourceField;
    private javax.swing.JLabel statsLabel;
    private javax.swing.JTextField statusField;
    private javax.swing.JTextField terrainField;
    private javax.swing.JTextField updatesField;
    // End of variables declaration//GEN-END:variables
}
