/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jeremy
 */
public class AtlasFrame extends javax.swing.JFrame {

    /**
     * Creates new form AtlasFrame
     */
    public AtlasFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameField = new javax.swing.JTextField();
        EnLabel = new javax.swing.JLabel();
        PrLabel = new javax.swing.JLabel();
        WeLabel = new javax.swing.JLabel();
        PoLabel = new javax.swing.JLabel();
        KnLabel = new javax.swing.JLabel();
        EnField = new javax.swing.JTextField();
        PrField = new javax.swing.JTextField();
        WeField = new javax.swing.JTextField();
        PoField = new javax.swing.JTextField();
        KnField = new javax.swing.JTextField();
        EnGoalField = new javax.swing.JTextField();
        PrGoalField = new javax.swing.JTextField();
        WeGoalField = new javax.swing.JTextField();
        PoGoalField = new javax.swing.JTextField();
        KnGoalField = new javax.swing.JTextField();
        statsLabel = new javax.swing.JLabel();
        goalsLabel = new javax.swing.JLabel();
        jSeparatorH = new javax.swing.JSeparator();
        jSeparatorV = new javax.swing.JSeparator();
        statusField = new javax.swing.JTextField();
        statusLabel = new javax.swing.JLabel();
        nationActionsLabel = new javax.swing.JLabel();
        EnHPButton = new javax.swing.JButton();
        PrHPButton = new javax.swing.JButton();
        WeHPButton = new javax.swing.JButton();
        KnHPButton = new javax.swing.JButton();
        PoHPButton = new javax.swing.JButton();
        nameAcceptButton = new javax.swing.JButton();
        playerActionsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adjTerList = new javax.swing.JList();
        adjTerLabel = new javax.swing.JLabel();
        adjTerrainLabel = new javax.swing.JLabel();
        adjResourceLabel = new javax.swing.JLabel();
        terrainField = new javax.swing.JTextField();
        resourceField = new javax.swing.JTextField();
        curTerLabel = new javax.swing.JLabel();
        curTerrainLabel = new javax.swing.JLabel();
        curResourceLabel = new javax.swing.JLabel();
        curTerField = new javax.swing.JTextField();
        curTerrainField = new javax.swing.JTextField();
        curResourceField = new javax.swing.JTextField();
        travelButton = new javax.swing.JButton();
        totalLabel = new javax.swing.JLabel();
        statsTotalField = new javax.swing.JTextField();
        goalsTotalField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparatorH1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        waterField = new javax.swing.JTextField();
        foodField = new javax.swing.JTextField();
        stoneField = new javax.swing.JTextField();
        metalField = new javax.swing.JTextField();
        woodField = new javax.swing.JTextField();
        propNameField = new javax.swing.JTextField();
        demoButton = new javax.swing.JButton();
        dictButton = new javax.swing.JButton();
        nationNameLabel = new javax.swing.JLabel();
        supportField = new javax.swing.JTextField();
        taxPropField = new javax.swing.JTextField();
        yesButton = new javax.swing.JButton();
        noButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        taxLabel = new javax.swing.JLabel();
        waterTax = new javax.swing.JTextField();
        foodTax = new javax.swing.JTextField();
        metalTax = new javax.swing.JTextField();
        stoneTax = new javax.swing.JTextField();
        woodTax = new javax.swing.JTextField();
        nationLabel = new javax.swing.JLabel();
        nationNameField = new javax.swing.JTextField();
        coupButton = new javax.swing.JButton();
        setTaxesLabel = new javax.swing.JLabel();
        waterTaxField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        foodTaxField = new javax.swing.JTextField();
        metalTaxField = new javax.swing.JTextField();
        stoneTaxField = new javax.swing.JTextField();
        woodTaxField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));
        setResizable(false);

        nameField.setForeground(new java.awt.Color(204, 0, 0));
        nameField.setText("Name");
        nameField.setName(""); // NOI18N
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        EnLabel.setText("Environment");

        PrLabel.setText("Privacy");

        WeLabel.setText("Wealth");

        PoLabel.setText("Power");

        KnLabel.setText("Knowledge");

        EnField.setEditable(false);
        EnField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EnField.setText("0");

        PrField.setEditable(false);
        PrField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PrField.setText("0");
        PrField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrFieldActionPerformed(evt);
            }
        });

        WeField.setEditable(false);
        WeField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        WeField.setText("0");

        PoField.setEditable(false);
        PoField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PoField.setText("0");

        KnField.setEditable(false);
        KnField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        KnField.setText("0");

        EnGoalField.setEditable(false);
        EnGoalField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EnGoalField.setText("0");

        PrGoalField.setEditable(false);
        PrGoalField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PrGoalField.setText("0");

        WeGoalField.setEditable(false);
        WeGoalField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        WeGoalField.setText("0");

        PoGoalField.setEditable(false);
        PoGoalField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PoGoalField.setText("0");

        KnGoalField.setEditable(false);
        KnGoalField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        KnGoalField.setText("0");

        statsLabel.setText(": Stats");

        goalsLabel.setText(": Goals");

        jSeparatorH.setForeground(new java.awt.Color(0, 0, 0));

        jSeparatorV.setForeground(new java.awt.Color(0, 0, 0));
        jSeparatorV.setOrientation(javax.swing.SwingConstants.VERTICAL);

        statusField.setEditable(false);
        statusField.setText("Nomad");
        statusField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusFieldActionPerformed(evt);
            }
        });

        statusLabel.setText("Status:");

        nationActionsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nationActionsLabel.setText("Nation Actions:");

        EnHPButton.setLabel("+HP");
        EnHPButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        EnHPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnHPButtonActionPerformed(evt);
            }
        });

        PrHPButton.setLabel("+HP");
        PrHPButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        PrHPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrHPButtonActionPerformed(evt);
            }
        });

        WeHPButton.setLabel("+HP");
        WeHPButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        WeHPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeHPButtonActionPerformed(evt);
            }
        });

        KnHPButton.setLabel("+HP");
        KnHPButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        KnHPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KnHPButtonActionPerformed(evt);
            }
        });

        PoHPButton.setLabel("+HP");
        PoHPButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        PoHPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PoHPButtonActionPerformed(evt);
            }
        });

        nameAcceptButton.setText("Accept");
        nameAcceptButton.setMargin(new java.awt.Insets(2, 2, 2, 2));

        playerActionsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        playerActionsLabel.setText("Player Actions:");

        jScrollPane1.setViewportView(adjTerList);

        adjTerLabel.setText("Adjacent Territories:");

        adjTerrainLabel.setText("Terrain:");

        adjResourceLabel.setText("Resource:");

        terrainField.setEditable(false);
        terrainField.setText("terrain");
        terrainField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terrainFieldActionPerformed(evt);
            }
        });

        resourceField.setEditable(false);
        resourceField.setText("resource");

        curTerLabel.setText("Current Territory:");

        curTerrainLabel.setText("Terrain:");

        curResourceLabel.setText("Resource:");

        curTerField.setEditable(false);
        curTerField.setText("origin");
        curTerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curTerFieldActionPerformed(evt);
            }
        });

        curTerrainField.setEditable(false);
        curTerrainField.setText("terrain");

        curResourceField.setEditable(false);
        curResourceField.setText("resource");

        travelButton.setText("Travel");
        travelButton.setMargin(new java.awt.Insets(2, 2, 2, 2));

        totalLabel.setText("Total");

        statsTotalField.setForeground(new java.awt.Color(0, 102, 0));
        statsTotalField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        statsTotalField.setText("0");

        goalsTotalField1.setForeground(new java.awt.Color(0, 0, 102));
        goalsTotalField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        goalsTotalField1.setText("0");

        jLabel1.setText("%");

        jLabel2.setText("%");

        jSeparatorH1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setText("Resources:");

        jLabel4.setText("Water:");

        jLabel5.setText("Food:");

        jLabel6.setText("Metal:");

        waterField.setEditable(false);
        waterField.setText("0");

        foodField.setEditable(false);
        foodField.setText("0");
        foodField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodFieldActionPerformed(evt);
            }
        });

        stoneField.setEditable(false);
        stoneField.setText("0");
        stoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stoneFieldActionPerformed(evt);
            }
        });

        metalField.setEditable(false);
        metalField.setText("0");

        woodField.setEditable(false);
        woodField.setText("0");

        propNameField.setText("jTextField1");

        demoButton.setText("Propose Democracy");
        demoButton.setMargin(new java.awt.Insets(2, 2, 2, 2));

        dictButton.setText("Propose Dictatorship");
        dictButton.setMargin(new java.awt.Insets(2, 2, 2, 2));

        nationNameLabel.setText("Nation Name:");

        supportField.setEditable(false);
        supportField.setText("player wants [support/vote] for ...");

        taxPropField.setEditable(false);
        taxPropField.setText("taxes: wood:0%, ...");

        yesButton.setText("Yes");

        noButton.setText("No");

        jLabel9.setText("Stone:");

        jLabel10.setText("Wood:");

        taxLabel.setText("Tax Rate(%):");

        waterTax.setEditable(false);
        waterTax.setText("0");

        foodTax.setEditable(false);
        foodTax.setText("0");

        metalTax.setEditable(false);
        metalTax.setText("0");

        stoneTax.setEditable(false);
        stoneTax.setText("0");

        woodTax.setEditable(false);
        woodTax.setText("0");

        nationLabel.setText("Your Nation:");

        nationNameField.setEditable(false);
        nationNameField.setText("nationname");
        nationNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nationNameFieldActionPerformed(evt);
            }
        });

        coupButton.setText("Propose Coup");
        coupButton.setMargin(new java.awt.Insets(2, 2, 2, 2));

        setTaxesLabel.setText("Set Taxes(%)");

        waterTaxField.setText("jTextField1");

        jLabel7.setText("Water:");

        jLabel8.setText("Food:");

        jLabel11.setText("Metal:");

        jLabel12.setText("Stone:");

        jLabel13.setText("Wood:");

        foodTaxField.setText("jTextField2");

        metalTaxField.setText("jTextField3");

        stoneTaxField.setText("jTextField4");

        woodTaxField.setText("jTextField5");

        jButton3.setText("Submit");

        panel1.setMaximumSize(new java.awt.Dimension(600, 450));
        panel1.setPreferredSize(new java.awt.Dimension(600, 450));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MapGraphic/MapHolder.png"))); // NOI18N
        jLabel14.setText("jLabel14");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel15.setText("NationName:");

        jTextField1.setEditable(false);
        jTextField1.setText("None");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(EnLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(PrLabel))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(EnHPButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(EnGoalField)
                                                    .addComponent(EnField))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(PrGoalField)
                                                    .addComponent(PrHPButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(PrField))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(WeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                            .addComponent(WeGoalField)
                                            .addComponent(WeField, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(WeHPButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nameAcceptButton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(PoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(PoGoalField)
                                            .addComponent(PoField)
                                            .addComponent(PoHPButton, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(KnField)
                                                    .addComponent(KnGoalField)
                                                    .addComponent(KnHPButton, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                                                .addGap(22, 22, 22)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(statsTotalField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(goalsTotalField1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(statsLabel)
                                                    .addComponent(goalsLabel)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(KnLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(totalLabel))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparatorV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparatorH, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nationNameLabel)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nationActionsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(propNameField)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nationLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nationNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dictButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(demoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(coupButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(supportField, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                .addComponent(taxPropField)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(yesButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(noButton)
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addComponent(jSeparatorH1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(waterTaxField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(foodTaxField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(metalTaxField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(stoneTaxField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(woodTaxField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton3)
                                    .addComponent(setTaxesLabel))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(travelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(48, 48, 48))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(adjResourceLabel)
                                            .addComponent(adjTerrainLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(terrainField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(resourceField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(playerActionsLabel)
                                    .addComponent(adjTerLabel))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(10, 10, 10)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(curTerLabel)
                                    .addComponent(curTerrainLabel)
                                    .addComponent(curResourceLabel)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(curTerrainField)
                                    .addComponent(curTerField)
                                    .addComponent(curResourceField, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                    .addComponent(jTextField1)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(107, 107, 107)
                                    .addComponent(foodTax, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(4, 4, 4)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel10)))
                                        .addComponent(jLabel4))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(stoneField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(metalField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(foodField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(waterField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(woodField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(22, 22, 22)
                                            .addComponent(waterTax, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(metalTax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(stoneTax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(woodTax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(taxLabel)))
                        .addContainerGap(11, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statusLabel)
                                    .addComponent(nameAcceptButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EnLabel)
                                    .addComponent(PrLabel)
                                    .addComponent(WeLabel)
                                    .addComponent(PoLabel)
                                    .addComponent(KnLabel)
                                    .addComponent(totalLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PrField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(WeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(KnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statsLabel)
                                    .addComponent(statsTotalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EnGoalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PrGoalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(WeGoalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PoGoalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(KnGoalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(goalsLabel)
                                    .addComponent(goalsTotalField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EnHPButton)
                                    .addComponent(PrHPButton)
                                    .addComponent(WeHPButton)
                                    .addComponent(KnHPButton)
                                    .addComponent(PoHPButton))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparatorV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparatorH, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nationActionsLabel)
                            .addComponent(supportField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(demoButton)
                            .addComponent(nationNameLabel)
                            .addComponent(taxPropField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dictButton)
                            .addComponent(propNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yesButton)
                            .addComponent(noButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(setTaxesLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(coupButton)
                            .addComponent(nationNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nationLabel)
                            .addComponent(waterTaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(foodTaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(metalTaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stoneTaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(woodTaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addGap(5, 5, 5)
                        .addComponent(jSeparatorH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playerActionsLabel)
                        .addGap(18, 18, 18)
                        .addComponent(adjTerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(adjTerrainLabel)
                                    .addComponent(terrainField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(resourceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adjResourceLabel))
                                .addGap(32, 32, 32)
                                .addComponent(travelButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(curTerLabel)
                            .addComponent(curTerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(curTerrainLabel)
                            .addComponent(curTerrainField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(curResourceLabel)
                            .addComponent(curResourceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(taxLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(waterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(waterTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(foodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(foodTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(metalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(metalTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(stoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stoneTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(woodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(woodTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrFieldActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void statusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusFieldActionPerformed

    private void EnHPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnHPButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnHPButtonActionPerformed

    private void PrHPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrHPButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrHPButtonActionPerformed

    private void WeHPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeHPButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WeHPButtonActionPerformed

    private void KnHPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KnHPButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KnHPButtonActionPerformed

    private void PoHPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PoHPButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PoHPButtonActionPerformed

    private void terrainFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terrainFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_terrainFieldActionPerformed

    private void curTerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curTerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_curTerFieldActionPerformed

    private void foodFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodFieldActionPerformed

    private void stoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stoneFieldActionPerformed

    private void nationNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nationNameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtlasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtlasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtlasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtlasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtlasFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EnField;
    private javax.swing.JTextField EnGoalField;
    private javax.swing.JButton EnHPButton;
    private javax.swing.JLabel EnLabel;
    private javax.swing.JTextField KnField;
    private javax.swing.JTextField KnGoalField;
    private javax.swing.JButton KnHPButton;
    private javax.swing.JLabel KnLabel;
    private javax.swing.JTextField PoField;
    private javax.swing.JTextField PoGoalField;
    private javax.swing.JButton PoHPButton;
    private javax.swing.JLabel PoLabel;
    private javax.swing.JTextField PrField;
    private javax.swing.JTextField PrGoalField;
    private javax.swing.JButton PrHPButton;
    private javax.swing.JLabel PrLabel;
    private javax.swing.JTextField WeField;
    private javax.swing.JTextField WeGoalField;
    private javax.swing.JButton WeHPButton;
    private javax.swing.JLabel WeLabel;
    private javax.swing.JLabel adjResourceLabel;
    private javax.swing.JLabel adjTerLabel;
    private javax.swing.JList adjTerList;
    private javax.swing.JLabel adjTerrainLabel;
    private javax.swing.JButton coupButton;
    private javax.swing.JTextField curResourceField;
    private javax.swing.JLabel curResourceLabel;
    private javax.swing.JTextField curTerField;
    private javax.swing.JLabel curTerLabel;
    private javax.swing.JTextField curTerrainField;
    private javax.swing.JLabel curTerrainLabel;
    private javax.swing.JButton demoButton;
    private javax.swing.JButton dictButton;
    private javax.swing.JTextField foodField;
    private javax.swing.JTextField foodTax;
    private javax.swing.JTextField foodTaxField;
    private javax.swing.JLabel goalsLabel;
    private javax.swing.JTextField goalsTotalField1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparatorH;
    private javax.swing.JSeparator jSeparatorH1;
    private javax.swing.JSeparator jSeparatorV;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField metalField;
    private javax.swing.JTextField metalTax;
    private javax.swing.JTextField metalTaxField;
    private javax.swing.JButton nameAcceptButton;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nationActionsLabel;
    private javax.swing.JLabel nationLabel;
    private javax.swing.JTextField nationNameField;
    private javax.swing.JLabel nationNameLabel;
    private javax.swing.JButton noButton;
    private java.awt.Panel panel1;
    private javax.swing.JLabel playerActionsLabel;
    private javax.swing.JTextField propNameField;
    private javax.swing.JTextField resourceField;
    private javax.swing.JLabel setTaxesLabel;
    private javax.swing.JLabel statsLabel;
    private javax.swing.JTextField statsTotalField;
    private javax.swing.JTextField statusField;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField stoneField;
    private javax.swing.JTextField stoneTax;
    private javax.swing.JTextField stoneTaxField;
    private javax.swing.JTextField supportField;
    private javax.swing.JLabel taxLabel;
    private javax.swing.JTextField taxPropField;
    private javax.swing.JTextField terrainField;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JButton travelButton;
    private javax.swing.JTextField waterField;
    private javax.swing.JTextField waterTax;
    private javax.swing.JTextField waterTaxField;
    private javax.swing.JTextField woodField;
    private javax.swing.JTextField woodTax;
    private javax.swing.JTextField woodTaxField;
    private javax.swing.JButton yesButton;
    // End of variables declaration//GEN-END:variables
}
